### PR TITLE
remove an xcode warning because publication changes were made in a bac…

### PR DESCRIPTION
**Pull request by avienne**
…kground thread.

Do not hesitate to give feedback it's my first time writing swift code (except while playing with tutos ^^)
Bug found while playing around with the registration flow.

### CODE REVIEW

**Comment by bourvill** [comment]
Well found!

Looking at the more ready code, I think both the error and the connected affect the rest of the interface.

Maybe replacing the $ state publisher would be better

```
appState.session. $ state.receive (on: DispatchQueue.main) .sink ...
```

ANd remove all DispatchQueue reference inside sink.


Do you want to try to do it?
Don't hesitate if you need help.
Thank you for participating in the project and for your first contribution

**Comment by avienne** [comment]
Changes done, not sure about the removal of [unowned self] (was not an optional anymore, xcode was complaining)

**Comment by bourvill** [comment]
Please keep [unowned self]

You can apply `swiftformat` tool on your file and PR can be merge

**Comment by avienne** [comment]
Should be ready to merge then

**Comment by bourvill** [comment]
Merged in release/5.0.2 public TestFlight with this change will be available soon

**Pull request merged**
