### PR TITLE
Themes

### PR DESCRIPTION
**Pull request by j0k3r**
Should fix https://github.com/wallabag/ios-app/issues/42
So, I've tried something. But it's far from perfect at the moment.

First of all, I run ImageOptim on all images, I saved almost 100% of their size 🙂

I renamed the default theme to `white` and updated both `night` & `light` theme.
I've tried to define a custom color in the ThemeManager:

```swift
return UIColor.init(red: 246, green: 239, blue: 220, alpha: 1)
```

But it doesn't seems to work. It's always displayed as white...

The background menu color doesn't seems to be configurable (like the whole settings pages), so it generated a hard to read one:
capture d ecran 2016-12-23 a 07 37 29

For the night theme, I changed the navBackground image to something less dark (and also the css) but it doesn't seems to be the exact same color:

capture d ecran 2016-12-23 a 07 36 58

And I've no idea why since both should be `#111`.

I did the same for the light theme and it works fine:

capture d ecran 2016-12-23 a 07 38 12

Questions are:
- could turn the background menu configurable?
- how can I define a custom color using `UIColor` that actually works and isn't a predefined one (like dark, gray, etc.)?

### CODE REVIEW

**Comment by j0k3r** [comment]
I've added a new dusk theme (less dark than the dark theme).

Others questions:
 - how can I change the title color (actually it's always black)?
 - how can I set a default color for the webview before it loads (actually it's always white)
 - can you turn the about page to use the theme color?

**Comment by bourvill** [comment]
@j0k3r i fix each point in separate commit. You can review ?

**Comment by j0k3r** [comment]
Excellent !

What could be possibly wrong with the color when the title doesn't seems to have the same color as the one defined in the CSS? Is that the same problem with the color bar?



One last thing, how can we configure the hover effect color when we select an item in the list? At the moment, when we select an item, the background goes light gray?

**Comment by bourvill** [comment]
@j0k3r I add a new property, you can easily define a new selected color for cell.

For the title, i dont know how i can solve this problem

**Pull request merged**
