### PR TITLE
Feature: Menu add gesture and opacity

### PR DESCRIPTION
**Pull request by avienne**
While playing around with SwiftUI (wanted to learn something) I thought this could be a small an easy improvement to UI/Ux of the menu. Please review it there are probably stuff I am doing wrong.

Basically I added a layer between the main VStack and the menu when it is open (to be able to tap on it)
Blurred the main VStack if the menu is open
Added a close gesture to be able to close the menu by swaping it left.

### CODE REVIEW

**Comment by avienne** [comment]
and if you want to merge it in another branch (or not) just tell me I can recreate the PR if it ease your work.

**Comment by bourvill** [comment]
Hello, 5.0.2 is frozen and I will be merged in master shortly.
When it’s merge I will change your branch.

I will test your work soon.

Thank for your contribution

**Comment by bourvill** [comment]
Having some issue with your branch due to the rebase merge of 5.0.2 in master

Can you rebase your branch from master please?

**Comment by avienne** [comment]
that should be ok now, I updated my master based on yours rebased this branch onto it.

**Comment by bourvill** [comment]
Capture d’écran 2020-05-11 à 09 55 47


Nice work! but on top of rectangle with have white border. I think `edgesIgnoringSafeArea` is missing can you try to arrange this?

**Comment by avienne** [comment]
well I played with this option and I think it's quite weird not to have the white rectangle at top. It's a matter of taste. I'll let you decide ^^. Here are a couple of screens

Capture d’écran 2020-05-11 à 11 30 22

Capture d’écran 2020-05-11 à 11 31 03

**Comment by bourvill** [comment]
The top white rectangle is strange, it's possible to arrange this ?

**Comment by avienne** [comment]
I'll test a little more this week (maybe extend the blurred rectangle or put the menu into a sheet as no "new" apple apps has this kind of menus).

**Comment by avienne** [comment]
i tried this, i am just not comfortable with the default bottom padding value of view menu if there is no value to geometry.safeAreaInsets.bottom. I did not find the default padding value when we use the .padding() modifier.
Here is the result : 

Capture d’écran 2020-05-11 à 15 55 50

**Comment by bourvill** [comment]
Your branch seem to be not rebased from master (28 commits from history),

Can you rebase your branch? or create new one and cherry pick your work. 

And I can be able to merge in release/5.1.0.

Thank

**Comment by bourvill** [comment]
closed in favor #285

**Pull request closed without merging**
