### PR TITLE
Start i18n

### PR DESCRIPTION
**Pull request by bourvill**
RFR to #89 and #90

### CODE REVIEW

**Comment by jlnostr** [comment]
In my opinion the "Wallabag" strings should be all set with the lowercase version to keep the wallabag branding correct :)
If wanted, I can change this on the en translation as well.

**Comment by bourvill** [comment]
Yes, it's true, you can change if you want. This is my problem every time. You are right. By chance @nicosomb , has not seen it yet lol

**Comment by jlnostr** [comment]
I think the app can be simply renamed to "wallabag". There is no need for "2 official". Then the app name would be in par with the other platforms.

But I don't know how Apple is handling the name conflict with the old app.

**Comment by bourvill** [comment]
We can not, an application already has the name wallabag on the appstore. And another one is called "Wallabag Pro", we are obliged to mark a difference :(

**Comment by jlnostr** [comment]
Oh well. Maybe @kevmeyer can release an update for the old app the last time, just to rename it to "wallabag legacy".

**Pull request merged**
